@startuml
'https://plantuml.com/class-diagram

package Core{
    class Entity{
    }
}

package UnoApp{
    enum Color{
        Blue
        Yellow
        Red
        Green,
        None
    }

    abstract class Card{
        Color color;
    }

    class NumberCard{
        int number;
    }

    class MustBuyCard{
        int amountToBuy;
    }

    class ReverseCard{
    }

    class JumpCard{
    }

    Entity <|-- Card
    Color <- Card
    Card <|--- NumberCard
    Card <|--- MustBuyCard
    Card <|--- ReverseCard
    Card <|--- JumpCard

    interface IAction{
        void Execute(Match CurrentMatch);
    }

    interface ITossAction{    
        void Execute(Match CurrentMatch);
    }

    MustBuyCard ..|> IAction
    JumpCard ..|> IAction
    ReverseCard ..|> ITossAction
    
    class Match{
    }

    note bottom of ITossAction : This is supposed to be called before the turn ends
    note bottom of IAction : This is supposed to be called before the turn begins

    IAction --> Match
    ITossAction --> Match
}
@enduml