@startuml
'https://plantuml.com/class-diagram

package Core
{
    class Engine{
        static std::vector<Entity*> Entities;
        static void Reserve(int size);
        static void InitEntity(Core::Entity* NewEntity);
        static void ClearEntities();
        static void RemoveEntity(Core::Entity* EntityToRemove);
        static void Tick();
    }

    class Entity{        
        Entity(const std::string& EntityName);
        const std::string& GetName();
        void Begin();
        void Tick();
        void Destroy();  
    }
    
    Engine --> Entity
    Entity --> Engine
    
    class Core{
        void RunEngine();
    }

    Core --> Engine
}

@enduml