@startuml
'https://plantuml.com/class-diagram

package Core
{
    class Engine{
        static std::vector<std::weak_ptr<Entity>> Entities;
        static void Reserve(int size);
        static void InitEntity(const std::weak_ptr<Entity>& newEntity);
        static void ClearEntities();
        static void Destroy(EntityPtr<Entity> entityToRemove);
        static void Tick();
    }

    class Entity{        
        Entity(const std::string& EntityName);
        const std::string& GetName();
        void Begin();
        void Tick();
    }

    Engine --> Entity
    Engine --> EntityPtr

    class EntityPtr{
        std::shared_ptr<Entity>* Instance;
        std::shared_ptr<int> RefCount;
        std::weak_ptr<TElement> get();
        bool IsValid();
        void reset();
    }

    class Core{
        void RunEngine();
        void CloseApp();
    }

    Core --> Engine
}

package UnoApp
{
    class GameLifecycleController{
        EntityPtr<Match> CurrentMatch;
        void StartNewGame();
        void Replay();
        void CloseGame();
    }
    
    class Player{
        std::vector<EntityPtr<Card>> CardsOnHand;
        bool HasYelled;
        int GetAmountOfCardsOnHand();
        bool PlayTurn();
        void BuyCards();
        void BuyDeckCard();
        void BuyTossedCard();
        CanYell();
        Yell();
    }

    class DeckController{
        const std::vector<EntityPtr<Card>> AllCards;
        std::stack<EntityPtr<Card>> TossedCards;
        std::stack<EntityPtr<Card>> CardsOnDeck;
        void CreateCards();
        void ShuffleDeckCards();
        void AddCardToDeck(Card* card);
        bool IsDeckEmpty();
        void ShuffleTossedCardsBackToDeck();
        std::weak_ptr<Card> GetTopCard();
    }

    enum ETurnFlow{
        CLOCKWISE
        ANTI-CLOCKWISE
    }
    
    enum EColor{
        Blue,
        Yellow,
        Red,
        Green,
        None
    }

    class Match{    
        int CurrentTurn;
        TurnFlow Flow;
        std::vector<EntityPtr<Player>> JoinedPlayers;        
        void StartNewMatch();
        void JoinPlayers();
        void CreateDeck();
        void SortCardsToPlayers();
        void SortFirstPlayerTurn();
        void PlayTurn();
        void ExecuteCardAction();      
        void ExecuteCardTossAction();  
        void SkipTurn();
        void ReverseFlow();
        bool IsMatchEnded();
        void FinishMatch();
    }
    
    class Round{
        int RoundIndex
        std::weak_ptr<Player> CurrentPlayer;
        std::weak_ptr<DeckController> Deck;
    }

    class Card{
    }

    interface IPostRoundAction{}
    
    interface ICustomRoundCard{}
    
    interface IMatchContext{}

    Entity <|-- GameLifecycleController
    GameLifecycleController --> Match

    Entity <|-- Player
    Entity <|-- Match
    Entity <|-- DeckController

    Player -> DeckController
    Match ---> Player
    Match ---> DeckController
    Match -> ETurnFlow
    Match --> Card
    Match --> Round
    Match --> IPostRoundAction
    IMatchContext <|-Match
    IMatchContext <-- IPostRoundAction
    ICustomRoundCard --> Round
    Match --> ICustomRoundCard
    Round --> Player
    Round --> DeckController
    Round -> Card
    Card -> EColor
    Card <- DeckController
    EColor <- DeckController
    EColor <- Match
    Card <- Player
}

@enduml